# introdução a pandas

In [14]:
# instalando pandas 

! pip install pandas -q

In [15]:
## importando a biblioteca pandas para análise
import pandas as pd

# lendo dados /dataset (arquivo de dados)
df =  pd.read_csv('../dados/dados_alunos.csv')

In [16]:
##
df

        nome  idade genero        curso  semestre  nota_final  faltas
0   Fernanda     22      F   Engenharia         7        8.85      21
1    Eduardo     28      M          ADS         1        6.49       9
2       Igor     24      M  Arquitetura         3        5.85       8
3       Igor     29      F  Arquitetura        10        5.65       7
4      Bruno     28      M  Arquitetura         7        8.64       5
..       ...    ...    ...          ...       ...         ...     ...
95    Helena     26      M          ADS         2        6.65      21
96    Carlos     20      F   Engenharia         8        9.33      24
97     Diana     27      M      Direito         1        9.31      17
98      Igor     27      F     Medicina         9        8.88      17
99    Carlos     22      F     Medicina         8        9.75      21

[100 rows x 7 columns]

In [17]:
## visualizando o inicio do dataframe

df.head()

       nome  idade genero        curso  semestre  nota_final  faltas
0  Fernanda     22      F   Engenharia         7        8.85      21
1   Eduardo     28      M          ADS         1        6.49       9
2      Igor     24      M  Arquitetura         3        5.85       8
3      Igor     29      F  Arquitetura        10        5.65       7
4     Bruno     28      M  Arquitetura         7        8.64       5

In [18]:
## visualizando o final da tabela
df.tail(20)

        nome  idade genero        curso  semestre  nota_final  faltas
80   Gustavo     22      F     Medicina         9        8.05      19
81     Bruno     32      F          ADS         6        5.85       9
82    Helena     28      F      Direito         2        6.03      19
83   Gustavo     32      F   Engenharia         3        8.79      27
84    Helena     21      M   Engenharia         9        5.77      12
85   Eduardo     23      M     Medicina         7        7.15       2
86     Diana     19      M          ADS         7        5.22      25
87      Igor     35      F   Engenharia         7        8.01      21
88  Fernanda     34      F     Medicina        10        9.58      29
89       Ana     21      F      Direito         4        8.25      19
90      Igor     31      M  Arquitetura         6        9.16      15
91   Eduardo     26      F     Medicina         6        5.30       2
92      Igor     19      F   Engenharia         1        8.52      16
93    Helena     21      M          ADS        10        5.15      21
94      Igor     18      F   Engenharia         7        9.14      28
95    Helena     26      M          ADS         2        6.65      21
96    Carlos     20      F   Engenharia         8        9.33      24
97     Diana     27      M      Direito         1        9.31      17
98      Igor     27      F     Medicina         9        8.88      17
99    Carlos     22      F     Medicina         8        9.75      21

In [19]:
## Isso verifica se a formatação da tabela está concistente até o fim

In [20]:
## mostra a quantidade de registros e séries (COLUNAS são de tabelas e SÉRIES de dataframes) 
df.shape

(100, 7)

In [21]:
## trás o panorama geral da base de dados(dataframe)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nome        100 non-null    str
 1   idade       100 non-null    int64
 2   genero      100 non-null    str
 3   curso       100 non-null    str
 4   semestre    100 non-null    int64
 5   nota_final  100 non-null    float64
 6   faltas      100 non-null    int64
dtypes: float64(1), int64(3), str(3)
memory usage: 5.6 KB