In [12]:
import pandas as pd

df = pd.read_csv('../dados/dataset_trabalho.csv')

display(df)

   id_cliente    pais observacoes  idade          cidade escolaridade  comprou
0         101  Brasil         NaN   24.0       São Paulo        Médio        0
1         102  Brasil         NaN    NaN  Rio de Janeiro    Graduação        1
2         103  Brasil         VIP   35.0        Curitiba          Pós        1
3         104  Brasil         NaN   48.0       São Paulo    Graduação        0
4         105  Brasil         NaN   22.0             NaN        Médio        0
5         106  Brasil         NaN   50.0  Rio de Janeiro          Pós        1
6         107  Brasil         NaN   31.0        Curitiba    Graduação        1
7         107  Brasil         NaN   31.0        Curitiba    Graduação        1

In [13]:
df.isnull().sum()

id_cliente      0
pais            0
observacoes     7
idade           1
cidade          1
escolaridade    0
comprou         0
dtype: int64

In [14]:
# Criar uma cópia para preservar o dataset original
df_tratado = df.copy()

# Tratar a idade com a mediana
mediana = df_tratado['idade'].median()
df_tratado['idade'] = df_tratado['idade'].fillna(mediana)

# Tratar a cidade com "Desconhecido"
df_tratado['cidade'] = df_tratado['cidade'].fillna('Desconhecido')

# Exibir o resultado
display(df_tratado)

   id_cliente    pais observacoes  idade          cidade escolaridade  comprou
0         101  Brasil         NaN   24.0       São Paulo        Médio        0
1         102  Brasil         NaN   31.0  Rio de Janeiro    Graduação        1
2         103  Brasil         VIP   35.0        Curitiba          Pós        1
3         104  Brasil         NaN   48.0       São Paulo    Graduação        0
4         105  Brasil         NaN   22.0    Desconhecido        Médio        0
5         106  Brasil         NaN   50.0  Rio de Janeiro          Pós        1
6         107  Brasil         NaN   31.0        Curitiba    Graduação        1
7         107  Brasil         NaN   31.0        Curitiba    Graduação        1

In [28]:
df_tratado = df_tratado.drop(columns=['observacoes'])

display(df_tratado)

   id_cliente    pais  idade          cidade escolaridade  comprou
0         101  Brasil   24.0       São Paulo        Médio        0
1         102  Brasil   31.0  Rio de Janeiro    Graduação        1
2         103  Brasil   35.0        Curitiba          Pós        1
3         104  Brasil   48.0       São Paulo    Graduação        0
4         105  Brasil   22.0    Desconhecido        Médio        0
5         106  Brasil   50.0  Rio de Janeiro          Pós        1
6         107  Brasil   31.0        Curitiba    Graduação        1
7         107  Brasil   31.0        Curitiba    Graduação        1

In [26]:
df_tratado.isnull().sum()

id_cliente      0
pais            0
idade           0
cidade          0
escolaridade    0
comprou         0
dtype: int64

In [27]:
df_tratado['observacoes'] = df['observacoes']