## Tipos de Variáveis 
 
# Objetivo:

- entender os tipos de variáveis
- diferrenciar variaveis numéricas, categoricas, binarias e temporarias
- exemplos praticos com pandas

In [71]:
! pip install pandas -q

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
import pandas as pd

In [73]:
dados = {
    "Nome":["Ana","Bruno","Daniel","Luciano"],
    "Idade":[23, 17, 25, 50],
    "Altura":[1.68, 1.78, 1.90, 2.05 ],
    "Curso":["engenharia","medicina","ADS","Direito"],
    "Escolaridade":["médio","superior","superior","medio"],
    "Aprovado":[True, True, False, True],
    "Data_matricula":["2023-01-10", "2020-09-21", "2023-01-11", "2022-01-15"]
     ##"Data_matricula":pd.to_datetime(["2023-01-10", "2020-09-21", "2023-01-11", "2022-01-15"])
}

df = pd.DataFrame(dados)

In [74]:
df

      Nome  Idade  Altura       Curso Escolaridade  Aprovado Data_matricula
0      Ana     23    1.68  engenharia        médio      True     2023-01-10
1    Bruno     17    1.78    medicina     superior      True     2020-09-21
2   Daniel     25    1.90         ADS     superior     False     2023-01-11
3  Luciano     50    2.05     Direito        medio      True     2022-01-15

In [75]:
df.tail()

      Nome  Idade  Altura       Curso Escolaridade  Aprovado Data_matricula
0      Ana     23    1.68  engenharia        médio      True     2023-01-10
1    Bruno     17    1.78    medicina     superior      True     2020-09-21
2   Daniel     25    1.90         ADS     superior     False     2023-01-11
3  Luciano     50    2.05     Direito        medio      True     2022-01-15

In [76]:
df.head()

      Nome  Idade  Altura       Curso Escolaridade  Aprovado Data_matricula
0      Ana     23    1.68  engenharia        médio      True     2023-01-10
1    Bruno     17    1.78    medicina     superior      True     2020-09-21
2   Daniel     25    1.90         ADS     superior     False     2023-01-11
3  Luciano     50    2.05     Direito        medio      True     2022-01-15

In [77]:
## tratando serie de data e convertendo para tipo date por que estava em string
df['Data_matricula'] = pd.to_datetime(df['Data_matricula'])

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nome            4 non-null      str
 1   Idade           4 non-null      int64
 2   Altura          4 non-null      float64
 3   Curso           4 non-null      str
 4   Escolaridade    4 non-null      str
 5   Aprovado        4 non-null      bool
 6   Data_matricula  4 non-null      datetime64[us]
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 328.0 bytes

In [79]:
df.shape

(4, 7)

# tipos de variaveis 

## numericas

- discretas: assume numeros inteiros 
- continua: assume numeros com intervalos de valores(float)(ex:altura e peso)

In [80]:
print("Idade (variavel numerica DISCRETA)") 
print(df['Idade'])
print("Altura (variavel numerica CONTINUA)") 
print(df["Altura"])

Idade (variavel numerica DISCRETA)
0    23
1    17
2    25
3    50
Name: Idade, dtype: int64
Altura (variavel numerica CONTINUA)
0    1.68
1    1.78
2    1.90
3    2.05
Name: Altura, dtype: float64

# variaveis categoricas

- Nominais: Não tem ordem ou hierarquia (ex: curso)
- Ordinais: Possuem ordem natural, ordem lógica ou hierarquica. (ex: escolaridade)

In [81]:
print("curso (variavel categorica nominal)") 
print(df['Curso'])
print("escolaridade (variavel categorica ordinal)") 
print(df["Escolaridade"])

curso (variavel categorica nominal)
0    engenharia
1      medicina
2           ADS
3       Direito
Name: Curso, dtype: str
escolaridade (variavel categorica ordinal)
0       médio
1    superior
2    superior
3       medio
Name: Escolaridade, dtype: str

# Variaveis Binarias

São variaveis, com apenas dois valores possiveis.

In [82]:
print("Aprovado (variavel binária)") 
print(df['Aprovado'])

Aprovado (variavel binária)
0     True
1     True
2    False
3     True
Name: Aprovado, dtype: bool

# variavel temporal.

representam tempo ou sequencia de eventos

In [83]:
print("Data_matricula (variavel temporal)") 
print(df['Data_matricula'])

Data_matricula (variavel temporal)
0   2023-01-10
1   2020-09-21
2   2023-01-11
3   2022-01-15
Name: Data_matricula, dtype: datetime64[us]